-- POPBY MVP DATABASE
-- Run this file in Supabase > SQL Editor.
-- PostGIS is expected in the `extensions` schema. If your project uses `gis`,
-- replace `extensions.` with `gis.` throughout before running it.

create extension if not exists postgis with schema extensions;

-- TABLES -------------------------------------------------------------------

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  suburb text not null default 'Fitzroy',
  lat double precision not null,
  lng double precision not null,
  geom extensions.geography(POINT, 4326) not null,
  created_at timestamptz not null default now()
);

create index if not exists locations_geom_idx
  on public.locations using gist (geom);

create table if not exists public.thoughts (
  id uuid primary key default gen_random_uuid(),
  location_id uuid not null references public.locations(id) on delete cascade,
  device_id uuid not null,
  category text not null check (
    category in ('Animals', 'Nature', 'Eat', 'Art', 'Place', 'Sound', 'Moment')
  ),
  body text,
  background_type text not null default 'solid',
  background_color text not null default 'white',
  font_family text not null default 'caveat',
  font_size smallint not null default 12,
  image_url text,
  music_url text check (
    music_url is null or music_url ~* '^https?://'
  ),
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.thoughts
  add column if not exists background_color text not null default 'white',
  add column if not exists font_family text not null default 'caveat',
  add column if not exists font_size smallint not null default 12;

update public.thoughts
set font_size = 12
where font_size = 10;

alter table public.thoughts
  alter column font_size set default 12;

alter table public.thoughts
  drop constraint if exists thoughts_background_type_check,
  drop constraint if exists thoughts_background_color_check,
  drop constraint if exists thoughts_font_family_check,
  drop constraint if exists thoughts_font_size_check;

alter table public.thoughts
  add constraint thoughts_background_type_check check (
    background_type in ('solid', 'lined', 'grid', 'dots', 'photo')
  ),
  add constraint thoughts_background_color_check check (
    background_color in ('white', 'sage', 'rose', 'clay', 'blue', 'lavender')
  ),
  add constraint thoughts_font_family_check check (
    font_family in ('caveat', 'patrick-hand', 'homemade-apple', 'island-moments')
  ),
  add constraint thoughts_font_size_check check (font_size in (12, 14, 16));

create index if not exists thoughts_location_idx
  on public.thoughts(location_id, created_at desc);

create index if not exists thoughts_device_idx
  on public.thoughts(device_id, created_at desc);

create table if not exists public.unlocks (
  device_id uuid not null,
  location_id uuid not null references public.locations(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key (device_id, location_id)
);

create table if not exists public.reports (
  thought_id uuid not null references public.thoughts(id) on delete cascade,
  device_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (thought_id, device_id)
);

create table if not exists public.dwell_events (
  id bigint generated by default as identity primary key,
  thought_id uuid not null references public.thoughts(id) on delete cascade,
  device_id uuid not null,
  ms integer not null check (ms >= 0 and ms <= 120000),
  created_at timestamptz not null default now()
);

-- SECURITY -----------------------------------------------------------------
-- Browser access goes through the security-definer functions below. There
-- are intentionally no direct app-table policies for anon/authenticated.

alter table public.locations enable row level security;
alter table public.thoughts enable row level security;
alter table public.unlocks enable row level security;
alter table public.reports enable row level security;
alter table public.dwell_events enable row level security;

drop policy if exists "read locations" on public.locations;
drop policy if exists "read visible thoughts" on public.thoughts;
drop policy if exists "read unlocks" on public.unlocks;

revoke all on table public.locations from anon, authenticated;
revoke all on table public.thoughts from anon, authenticated;
revoke all on table public.unlocks from anon, authenticated;
revoke all on table public.reports from anon, authenticated;
revoke all on table public.dwell_events from anon, authenticated;

-- MAP DATA -----------------------------------------------------------------

drop function if exists public.get_map_locations();
drop function if exists public.get_map_locations(uuid);

create function public.get_map_locations(p_device_id uuid)
returns table (
  location_id uuid,
  suburb text,
  lat double precision,
  lng double precision,
  thought_count bigint,
  dominant_category text,
  latest_at timestamptz,
  is_mine boolean,
  is_unlocked boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    l.id as location_id,
    l.suburb,
    l.lat,
    l.lng,
    count(t.id)::bigint as thought_count,
    (
      select t2.category
      from public.thoughts t2
      where t2.location_id = l.id
        and t2.hidden = false
      group by t2.category
      order by count(*) desc, max(t2.created_at) desc
      limit 1
    ) as dominant_category,
    max(t.created_at) as latest_at,
    bool_or(t.device_id = p_device_id) as is_mine,
    exists (
      select 1
      from public.unlocks u
      where u.location_id = l.id
        and u.device_id = p_device_id
    ) as is_unlocked
  from public.locations l
  join public.thoughts t
    on t.location_id = l.id
   and t.hidden = false
  group by l.id, l.suburb, l.lat, l.lng
  order by latest_at desc;
$$;

revoke all on function public.get_map_locations(uuid) from public;
grant execute on function public.get_map_locations(uuid) to anon;

-- LOCATION CARDS -----------------------------------------------------------

drop function if exists public.get_location_thoughts(uuid, uuid, boolean);

create function public.get_location_thoughts(
  p_location_id uuid,
  p_device_id uuid,
  p_mine_only boolean
)
returns table (
  id uuid,
  category text,
  body text,
  background_type text,
  background_color text,
  font_family text,
  font_size smallint,
  image_url text,
  music_url text,
  created_at timestamptz,
  is_own boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    t.id,
    t.category,
    t.body,
    t.background_type,
    t.background_color,
    t.font_family,
    t.font_size,
    t.image_url,
    t.music_url,
    t.created_at,
    (t.device_id = p_device_id) as is_own
  from public.thoughts t
  where t.location_id = p_location_id
    and t.hidden = false
    and (
      (p_mine_only = true and t.device_id = p_device_id)
      or
      (
        p_mine_only = false
        and exists (
          select 1
          from public.unlocks u
          where u.location_id = p_location_id
            and u.device_id = p_device_id
        )
      )
    )
  order by t.created_at desc;
$$;

revoke all on function public.get_location_thoughts(uuid, uuid, boolean) from public;
grant execute on function public.get_location_thoughts(uuid, uuid, boolean) to anon;

-- SUBURB PROGRESS -----------------------------------------------------------

create or replace function public.get_suburb_progress(p_suburb text)
returns table (
  active_locations bigint,
  total_thoughts bigint,
  unique_contributors bigint,
  successful_unlocks bigint,
  progress double precision
)
language sql
stable
security definer
set search_path = ''
as $$
  with stats as (
    select
      (
        select count(*)
        from public.locations l
        where l.suburb = p_suburb
          and exists (
            select 1
            from public.thoughts t
            where t.location_id = l.id
              and t.hidden = false
          )
      )::bigint as active_locations,
      (
        select count(*)
        from public.thoughts t
        join public.locations l on l.id = t.location_id
        where l.suburb = p_suburb
          and t.hidden = false
      )::bigint as total_thoughts,
      (
        select count(distinct t.device_id)
        from public.thoughts t
        join public.locations l on l.id = t.location_id
        where l.suburb = p_suburb
          and t.hidden = false
      )::bigint as unique_contributors,
      (
        select count(*)
        from public.unlocks u
        join public.locations l on l.id = u.location_id
        where l.suburb = p_suburb
      )::bigint as successful_unlocks
  )
  select
    active_locations,
    total_thoughts,
    unique_contributors,
    successful_unlocks,
    least(
      active_locations / 15.0,
      total_thoughts / 50.0,
      unique_contributors / 30.0,
      successful_unlocks / 50.0,
      1.0
    )::double precision as progress
  from stats;
$$;

revoke all on function public.get_suburb_progress(text) from public;
grant execute on function public.get_suburb_progress(text) to anon;

-- UNLOCK -------------------------------------------------------------------
-- User GPS is constructed in memory, checked, and never stored.

create or replace function public.record_unlock(
  p_device_id uuid,
  p_location_id uuid,
  p_user_lat double precision,
  p_user_lng double precision
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user extensions.geography;
  v_location extensions.geography;
begin
  v_user := extensions.st_setsrid(
    extensions.st_makepoint(p_user_lng, p_user_lat), 4326
  )::extensions.geography;

  select l.geom
    into v_location
  from public.locations l
  where l.id = p_location_id;

  if v_location is null then
    raise exception 'Location not found';
  end if;

  if not extensions.st_dwithin(v_user, v_location, 50) then
    raise exception 'Get closer';
  end if;

  insert into public.unlocks(device_id, location_id)
  values (p_device_id, p_location_id)
  on conflict do nothing;

  return true;
end;
$$;

revoke all on function public.record_unlock(
  uuid, uuid, double precision, double precision
) from public;
grant execute on function public.record_unlock(
  uuid, uuid, double precision, double precision
) to anon;

-- PUBLISH THOUGHT -----------------------------------------------------------
-- Raw Drop and user GPS values are validation-only function parameters. The
-- only persisted coordinate is the privacy-adjusted Safe Anchor (or a nearby
-- existing node selected by the 20m merge).

create or replace function public.is_supported_music_url(p_url text)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select
    p_url is null
    or btrim(p_url) = ''
    or btrim(p_url) ~* '^https://open[.]spotify[.]com/track/[a-z0-9]+/?$'
    or btrim(p_url) ~* '^https://music[.]apple[.]com/[a-z]{2}/song/[^/?#[:space:]]+/[0-9]+/?$'
    or btrim(p_url) ~* '^https://music[.]apple[.]com/[a-z]{2}/album/[^/?#[:space:]]+/[0-9]+[?]i=[0-9]+$'
    or btrim(p_url) ~* '^https://music[.]youtube[.]com/watch[?]v=[a-z0-9_-]+$';
$$;

drop function if exists public.publish_thought(
  uuid, double precision, double precision, double precision, double precision,
  double precision, double precision, text, text, text, text, text, text
);

drop function if exists public.publish_thought(
  uuid, double precision, double precision, double precision, double precision,
  double precision, double precision, text, text, text, text, text, text,
  smallint, text, text
);

drop function if exists public.publish_thought(
  uuid, double precision, double precision, double precision, double precision,
  double precision, double precision, text, text, text, text, text, text,
  smallint, text, text, uuid
);

create function public.publish_thought(
  p_device_id uuid,
  p_user_lat double precision,
  p_user_lng double precision,
  p_drop_lat double precision,
  p_drop_lng double precision,
  p_safe_lat double precision,
  p_safe_lng double precision,
  p_suburb text,
  p_category text,
  p_body text default null,
  p_background_type text default 'solid',
  p_background_color text default 'white',
  p_font_family text default 'caveat',
  p_font_size smallint default 12,
  p_image_url text default null,
  p_music_url text default null,
  p_target_location_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user extensions.geography;
  v_drop extensions.geography;
  v_safe extensions.geography;
  v_location_id uuid;
  v_thought_id uuid;
  v_count integer;
  v_word_count integer;
begin
  if p_suburb is distinct from 'Fitzroy' then
    raise exception 'Awaiting unlock';
  end if;

  if p_category is null
    or p_category not in ('Animals', 'Nature', 'Eat', 'Art', 'Place', 'Sound', 'Moment') then
    raise exception 'Invalid category';
  end if;

  if p_background_type is null
    or p_background_type not in ('solid', 'lined', 'grid', 'dots', 'photo') then
    raise exception 'Invalid background';
  end if;

  if p_background_color is null
    or p_background_color not in ('white', 'sage', 'rose', 'clay', 'blue', 'lavender') then
    raise exception 'Invalid background color';
  end if;

  if p_font_family is null
    or p_font_family not in ('caveat', 'patrick-hand', 'homemade-apple', 'island-moments') then
    raise exception 'Invalid font';
  end if;

  if p_font_size is null or p_font_size not in (12, 14, 16) then
    raise exception 'Invalid font size';
  end if;

  v_word_count := case
    when btrim(coalesce(p_body, '')) = '' then 0
    else cardinality(regexp_split_to_array(btrim(p_body), '[[:space:]]+'))
  end;

  if v_word_count > 150 then
    raise exception '150-word maximum';
  end if;

  if char_length(coalesce(p_music_url, '')) > 300 then
    raise exception 'Music link is too long';
  end if;

  if not public.is_supported_music_url(p_music_url) then
    raise exception 'Invalid music link';
  end if;

  v_user := extensions.st_setsrid(
    extensions.st_makepoint(p_user_lng, p_user_lat), 4326
  )::extensions.geography;

  v_drop := extensions.st_setsrid(
    extensions.st_makepoint(p_drop_lng, p_drop_lat), 4326
  )::extensions.geography;

  v_safe := extensions.st_setsrid(
    extensions.st_makepoint(p_safe_lng, p_safe_lat), 4326
  )::extensions.geography;

  if not extensions.st_dwithin(v_user, v_drop, 50) then
    raise exception 'Drop within 50m of your current location';
  end if;

  if not extensions.st_dwithin(v_drop, v_safe, 60) then
    raise exception 'Privacy anchor is too far from the original drop';
  end if;

  select count(*)
    into v_count
  from public.thoughts t
  where t.device_id = p_device_id
    and t.created_at > now() - interval '1 hour';

  if v_count >= 5 then
    raise exception 'Hourly drop limit reached';
  end if;

  if p_target_location_id is not null then
    select l.id
      into v_location_id
    from public.locations l
    where l.id = p_target_location_id
      and l.suburb = 'Fitzroy'
      and extensions.st_dwithin(l.geom, v_safe, 20);

    if v_location_id is null then
      raise exception 'Selected location is no longer available';
    end if;
  else
    select l.id
      into v_location_id
    from public.locations l
    where extensions.st_dwithin(l.geom, v_safe, 20)
    order by extensions.st_distance(l.geom, v_safe)
    limit 1;
  end if;

  if v_location_id is null then
    insert into public.locations (suburb, lat, lng, geom)
    values (p_suburb, p_safe_lat, p_safe_lng, v_safe)
    returning id into v_location_id;
  end if;

  select count(*)
    into v_count
  from public.thoughts t
  where t.location_id = v_location_id
    and t.created_at > now() - interval '1 hour';

  if v_count >= 3 then
    raise exception 'This location is taking a short break';
  end if;

  insert into public.thoughts (
    location_id,
    device_id,
    category,
    body,
    background_type,
    background_color,
    font_family,
    font_size,
    image_url,
    music_url
  )
  values (
    v_location_id,
    p_device_id,
    p_category,
    nullif(btrim(p_body), ''),
    p_background_type,
    p_background_color,
    p_font_family,
    p_font_size,
    p_image_url,
    nullif(btrim(p_music_url), '')
  )
  returning id into v_thought_id;

  return v_thought_id;
end;
$$;

revoke all on function public.publish_thought(
  uuid, double precision, double precision, double precision, double precision,
  double precision, double precision, text, text, text, text, text, text,
  smallint, text, text, uuid
) from public;
grant execute on function public.publish_thought(
  uuid, double precision, double precision, double precision, double precision,
  double precision, double precision, text, text, text, text, text, text,
  smallint, text, text, uuid
) to anon;

-- REPORT -------------------------------------------------------------------

create or replace function public.report_thought(
  p_device_id uuid,
  p_thought_id uuid
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_count integer;
begin
  insert into public.reports(thought_id, device_id)
  values (p_thought_id, p_device_id)
  on conflict do nothing;

  select count(*)::integer
    into v_count
  from public.reports r
  where r.thought_id = p_thought_id;

  if v_count >= 2 then
    update public.thoughts t
    set hidden = true
    where t.id = p_thought_id;
  end if;

  return v_count;
end;
$$;

revoke all on function public.report_thought(uuid, uuid) from public;
grant execute on function public.report_thought(uuid, uuid) to anon;

-- OWNER DELETE -------------------------------------------------------------

create or replace function public.delete_thought(
  p_device_id uuid,
  p_thought_id uuid
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.thoughts t
  where t.id = p_thought_id
    and t.device_id = p_device_id;

  if not found then
    raise exception 'Thought not found';
  end if;

  return true;
end;
$$;

revoke all on function public.delete_thought(uuid, uuid) from public;
grant execute on function public.delete_thought(uuid, uuid) to anon, authenticated;

-- DWELL --------------------------------------------------------------------

create or replace function public.record_dwell(
  p_device_id uuid,
  p_thought_id uuid,
  p_ms integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_ms is null or p_ms < 0 or p_ms > 120000 then
    return;
  end if;

  insert into public.dwell_events(thought_id, device_id, ms)
  values (p_thought_id, p_device_id, p_ms);
end;
$$;

revoke all on function public.record_dwell(uuid, uuid, integer) from public;
grant execute on function public.record_dwell(uuid, uuid, integer) to anon;

-- STORAGE ------------------------------------------------------------------
-- Anonymous uploads are an explicit hackathon compromise. Harden this with
-- signed uploads and stronger abuse controls before production.

insert into storage.buckets (id, name, public)
values ('thought-images', 'thought-images', true)
on conflict (id) do update set public = true;

drop policy if exists "anon upload thought images" on storage.objects;
create policy "anon upload thought images"
on storage.objects for insert to anon
with check (bucket_id = 'thought-images');

drop policy if exists "anon read thought images" on storage.objects;
create policy "anon read thought images"
on storage.objects for select to anon
using (bucket_id = 'thought-images');
