import { AnimatePresence, motion } from "framer-motion";
import { AlertCircle, BarChart3, BookOpen, ChevronLeft, ChevronRight, Compass, DollarSign, Footprints, Sparkles, Users } from "lucide-react";
import { useEffect, useState } from "react";

type Slide = { eyebrow: string; title: string; italic: string; copy: string; source: string; icon: typeof Users; content: React.ReactNode };
const card = (number: string, heading: string, body: string, source?: string) => <article className="card"><strong>{number}</strong><h3>{heading}</h3><p>{body}</p>{source && <small>{source}</small>}</article>;

const slides: Slide[] = [
  {
    eyebrow: "01 / MARKET POSITIONING", source: "", icon: Users, title: "A generation that", italic: "wants softer connection", copy: "They want company. They do not want the pressure of a plan, a performance or a reply.", content: <div className="split"><article className="warm-card"><span>CORE AUDIENCE</span><h3>18–25<br />Gen Z</h3><p>Students and early-career people moving through a city while holding their boundaries close.</p></article><article className="spectrum"><span>WHERE POPBY SITS</span><div><p>Solitude<small>isolated</small></p><b>Ambient connection<small>PopBy</small></b><p>Active socialising<small>high pressure</small></p></div></article></div>
    
  },
  { eyebrow: "02 / RESEARCH & EVIDENCE", source: "EVIDENCE  Ending Loneliness Together · Orygen · headspace · ABS · AIHW", icon: BarChart3, title: "Loneliness can feel", italic: "very public", copy: "Even when people are connected online, the pressure to look fine can make genuine presence feel further away.", content: <div className="cards compact">{card("> 40%", "Chronic loneliness", "15–24 year olds report the highest rates.", "Ending Loneliness Together & Orygen")}{card("60–62%", "Excluded", "Many feel a lack of companionship.", "Headspace youth survey")}{card("2×", "Need for safety", "Young women report greater social anxiety.", "ABS & AIHW")}{card("Quiet", "Performance fatigue", "Connection should not be another audition.", "Orygen")}</div> },
  { eyebrow: "03 / MARKET SIGNALS", source: "EVIDENCE  ABS Consumer Price Index · RACGP · AusPlay", icon: Footprints, title: "The city became", italic: "the plan", copy: "When a casual night out costs more, a walk is still a way to leave the room and meet the world.", content: <div className="cards three compact">{card("01", "Cost", "A walk stays free when a meetup does not.")}{card("02", "Micro-outdoors", "A small route can shift the whole day.")}{card("03", "Solo, not isolated", "Going alone still leaves room for presence.")}</div> },
  { eyebrow: "04 / ACADEMIC FOUNDATION", source: "FOUNDATION  Scannell & Gifford · Urban Belonging Photo App · Levordashka & Utz", icon: BookOpen, title: "A place becomes real", italic: "when feeling stays", copy: "A corner, a bench, a street. Meaning arrives when people leave a small part of themselves there.", content: <div className="quote"><span>PLACE ATTACHMENT</span><blockquote>“A physical space becomes a lived place through the fragments people attach to it.”</blockquote><p>Scannell & Gifford</p></div> },
  {
    eyebrow: "05 / USER PAIN POINTS", source: "", icon: AlertCircle, title: "Four reasons to", italic: "stay home", copy: "The barriers are not a lack of desire. They are the weight that arrives before a simple hello.", content: <div className="pain-copy"><b>PopBy makes the first step smaller.</b><p>Location turns a vague wish for connection into a small, low-pressure moment in the world outside.</p></div>
    
  }
];

function Person({ className = "" }: { className?: string }) { return <div className={`person ${className}`}><i /><b /><span /><em /></div>; }
function Scene({ index }: { index: number }) {
  if (index === 0) return <div className="scene persona-scene"><div className="window" /><motion.div animate={{ y: [0, -7, 0] }} transition={{ duration: 3.5, repeat: Infinity }} className="thought">“Maybe I’ll take the long way home.”</motion.div><Person className="persona-main" /><Person className="persona-friend" /><div className="plant" /><p>commuting, waiting,<br />wanting a gentler way in</p></div>;
  if (index === 1) return <div className="scene bench-scene"><div className="phone">notifications<br /><b>29</b></div><div className="bench" /><Person className="bench-person" /><motion.div animate={{ opacity: [.35, 1, .35], y: [0, -9, 0] }} transition={{ duration: 3, repeat: Infinity }} className="quiet-heart">♥</motion.div><p>surrounded by signals,<br />still feeling unseen</p></div>;
  if (index === 2) return <div className="scene walk-scene"><div className="cafe">$</div><div className="tree" /><div className="sidewalk" /><motion.div animate={{ x: [0, 52, 0] }} transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }}><Person className="walk-person" /></motion.div><div className="dog"><i /><b /></div><p>the cheapest plan<br />is a walk around the block</p></div>;
  if (index === 3) return <div className="scene place-scene"><div className="corner-building"><b>GROCER</b></div><div className="memory-note">I came here after<br />my first interview.</div><motion.div animate={{ scale: [.92, 1.06, .92] }} transition={{ duration: 2.7, repeat: Infinity }} className="pin">✦</motion.div><Person className="place-person" /><p>the city remembers<br />what we attach to it</p></div>;
  return <div className="scene pain-scene"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" /><b className="pain-layer layer-emotional">EMOTIONAL</b><b className="pain-layer layer-financial">FINANCIAL</b><b className="pain-layer layer-behavioural">BEHAVIOURAL</b><b className="pain-layer layer-contextual">CONTEXTUAL</b><span className="pain-word word-one">THE COST</span><span className="pain-word word-two">SAFETY</span><span className="pain-word word-three">WHO TO ASK?</span><span className="pain-word word-four">REPLY NOW</span><span className="pain-word word-five">TOO MUCH</span><span className="pain-word word-six">WHAT IF?</span><span className="pain-word word-seven">BOUNDARIES</span><span className="pain-word word-eight">NO PLAN</span><motion.div animate={{ rotate: 360 }} transition={{ duration: 24, repeat: Infinity, ease: "linear" }} className="pain-center"><AlertCircle size={42} /><b>THE<br />WEIGHT</b></motion.div><p>the barriers arrive<br />before the invitation</p></div>;
}

export default function App() {
  const [current, setCurrent] = useState(0);
  const advance = (amount: number) => setCurrent(value => Math.max(0, Math.min(slides.length - 1, value + amount)));
  useEffect(() => { const handle = (event: KeyboardEvent) => { if (event.key === "ArrowRight" || event.key === " ") advance(1); if (event.key === "ArrowLeft") advance(-1); }; window.addEventListener("keydown", handle); return () => window.removeEventListener("keydown", handle); }, []);
  const slide = slides[current]; const Icon = slide.icon;
  return <main><header><div className="brand">PopBy<span>.</span></div><div className="deck-name">RESEARCH &amp; PROBLEM DECK</div><div className="progress">0{current + 1} / 0{slides.length}</div></header><section className="stage"><AnimatePresence mode="wait"><motion.div key={current} initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -18 }} transition={{ duration: .42 }} className="copy"><p className="eyebrow"><Icon size={15} />{slide.eyebrow}</p><h1>{slide.title}<br /><em>{slide.italic}</em></h1><p className="intro">{slide.copy}</p><div className="content">{slide.content}</div><p className="source-label">{slide.source}</p></motion.div></AnimatePresence><motion.div key={`scene-${current}`} initial={{ opacity: 0, rotate: 4, scale: .94 }} animate={{ opacity: 1, rotate: 0, scale: 1 }} transition={{ duration: .6 }}><Scene index={current} /></motion.div></section><footer><button onClick={() => advance(-1)} disabled={!current}><ChevronLeft size={18} />Previous</button><div className="dots">{slides.map((_, index) => <button aria-label={`Go to slide ${index + 1}`} onClick={() => setCurrent(index)} className={index === current ? "active" : ""} key={index} />)}</div><button className="next" onClick={() => advance(1)} disabled={current === slides.length - 1}>Next<ChevronRight size={18} /></button></footer></main>;
}
